### ISSUE TITLE
Default shell configuration

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#1074]
Of course the recommended shell on IBM i is bash.

Perhaps we need:

1. a command to allows the user to change their default shell to bash
2. check the default shell when the user connects to the system, prompt if it's a dumb shell

These checks would happen in `IBMi#connect` (inside of `IBMi.ts`)

**Comment by beckhamrryyaann** [comment]
This looks fun.  I will try to implement this.

**Comment by beckhamrryyaann** [comment]
@worksofliam Hi,  Let me know if this is what you are expecting:  Please advise.
In the connect method of IBMi.ts
* It appears I can use the `sendCommand()` property to send commands to system.  I can run the command `echo $SHELL` and that will give me path of users current shell. 
*  If the value is equal to `/QOpenSys/pkgs/bin/bash` than I know they are using the correct shell.
*   If not, I send show Alert dialog that lets them press 'Yes'.
*  If Yes is pressed, then I can send the sql command, `CALL QSYS2.SET_PASE_SHELL_INFO('*DEFAULT', '/QOpenSys/pkgs/bin/bash')` to set their shell to use bash.

Thanks
Ryan

**Comment by worksofliam** [comment]
@beckhamrryyaann that sounds about right! Thanks for looking into this. I am looking forward to seeing your PR.

**Comment by beckhamrryyaann** [comment]
I about had the pr ready but got to thinking I just can’t assume bash is installed on system So i am working through that.

**Comment by chrjorgensen** [comment]
@beckhamrryyaann Closed by #1134

**Comment by worksofliam** [comment]
@ThomasBarberot Is your environment setup as defined in the CCSID docs? https://halcyon-tech.github.io/docs/#/pages/tips/ccsid

**Comment by ThomasBarberot** [comment]
Yes, that why I'm surprised.
- The system value QCCSID is set to 1147
- My user profil is set to CCSID(*SYSVAL)
- The system level environment variable PASE_LANG is set to FR_FR
- The system level environment variable QIBM_PASE_CCSID is set to 1208
When I change the default QSH to bash, there is an issue, and when I reset it to the default value, all working good.

**Comment by chrjorgensen** [comment]
@ThomasBarberot I don't see how `bash` could affect the download and upload of members - it's just a PASE program like the default `bsh` shell program and doesn't change the settings of the PASE environment.

You mention 'the default QSH' - but QSH is QSHELL, an EBCDIC environment, where `bash` and `bsh` run in PASE, an ASCII environment. VS Code connects to PASE - and only calls QSHELL for some operations - so VS Code sees the same environment, whatever your shell program is.

I would like to investigate this, but in order to be able to replicate your situation I need the following information:
- IBM i version
- bash version (output from `bash --version` in a PASE terminal, e.g. Terminals in Code for IBM i)
- System value setting (`WRKSYSVAL SYSVAL(*SYSCTL) OUTPUT(*PRINT)`)
- System environment variable (`WRKENVVAR LEVEL(*SYS)` and output from F16)
- Source file CCSID
- Correct display of characters (SEU?)
- Wrong display of characters (VS Code?)
- Settings in VS Code: SQL enabled? source dates enabled?

Thanks.

**Comment by ThomasBarberot** [comment]
Hi Christian.
Here are the requested informations :

- IBM i version: V7R3
- Bash version: 5.1.8(1)-release (powerpc-ibm-os400)
- System value setting: see attached file
- System environment variable: see attached file
- Source file CCSID: 297
- Correct display of characters (SEU?): see attached images for SEU
- Wrong display of characters (VS Code?): see attached images for VSC
- Settings in VS Code: SQL enabled? source dates enabled?: yes and yes and
see attached images for VSC settings

Thanks.

**Comment by chrjorgensen** [comment]
@ThomasBarberot I don't see any attached files or images...?

**Comment by ThomasBarberot** [comment]
Hi Christian.
I replied by email with attachments, but they are not registered. I tried to modify the post.
Thanks

**Comment by chrjorgensen** [comment]
@ThomasBarberot Thanks, I got your settings.

First thing to catch my eye is that you've enabled the setting `Support EBCDIC streamfiles`... this should not be necessary, since your SSH daemon setup already produces UTF-8 streamfiles and this setting adds another layer of conversion by calling `iconv` during download and upload of source members.

I have never used this setting, and I did a simple experiment to see what would happen:
1. I created a source file with CCSID 1147 and kept my remaining settings of CCSID 277 (Danish).
2. I added some lines with accent characters to the source file using SQL in CCSID 1147: 
![billede](https://user-images.githubusercontent.com/13275072/229622002-e9050667-541d-4e5b-b98e-9e7d718f952f.png)
3. I opened the member in VS Code: 
![billede](https://user-images.githubusercontent.com/13275072/229622135-65375f79-5048-476b-9b96-c6afda9637ff.png)

As seen, the characters was transferred correctly, no issues. And my shell is `/QOpenSys/pkgs/bin/bash`...

I suspect the setting `Support EBCDIC streamfiles` is the real issue here - and would strongly advice to disable this.

**Comment by chrjorgensen** [comment]
@ThomasBarberot Okay, let's look at the source in EBCDIC:

Please run `DSPPFM <lib>/<sourcefile> <member>` and press `F10` and specify command `W13` to show the hex values in the source lines. Check the hex codes for the accented characters - here is my example:

![billede](https://user-images.githubusercontent.com/13275072/230057074-b266d73e-ab39-4550-9292-44d9419ac94b.png)

The hex values should correspond to the values in this [CCSID 297](https://en.everybodywiki.com/EBCDIC_297) table.

**Comment by ThomasBarberot** [comment]
It's the same for me :
![image](https://user-images.githubusercontent.com/123751292/230105768-e792744b-114f-4f49-a83f-bd1af9f309fe.png)
"C0" for "é"

**Comment by chrjorgensen** [comment]
@ThomasBarberot Okay, next steps:

1. `DSPFD AMSSAMPLE/QRPGLESRC` and cut-and-paste the line with CCSID here.
2. Get the environment variables for the SSH daemon by following these steps:
    a. `NETSTAT *CNN`
    b. Press `F15` and enter `22` in lower value for `Local port range`
    c. On the job with `*` in Remote Address and Remote port, enter `8=Display jobs`
    d. Enter `5=Work with job`
    e. Enter `22. Display environment variables`
    f. Dump the displayed values here for all screens.

**Comment by ThomasBarberot** [comment]
Hi Chritian.

the CCSID of QRPGLESRC : 297
![image](https://user-images.githubusercontent.com/123751292/230290657-3f9f0d9f-188b-4d67-bb99-bbb27944c156.png)

The environment variables for the job (they are all in CCSID 1147) :
![image](https://user-images.githubusercontent.com/123751292/230292036-7c1b40a4-d854-4859-9a24-5d3f41dd6f96.png)
![image](https://user-images.githubusercontent.com/123751292/230292760-fd5d74fe-384b-408a-8728-56eac597f96a.png)
And the 3 longest variables :
![image](https://user-images.githubusercontent.com/123751292/230292842-f8e00c2a-040e-4f6c-8d21-0f853f939098.png)
![image](https://user-images.githubusercontent.com/123751292/230292858-af29f12d-a2e5-4093-aaba-70b260283434.png)
![image](https://user-images.githubusercontent.com/123751292/230292869-e28bec83-5b4a-4065-afce-ca3094a52fd1.png)
