### ISSUE TITLE
Replace SQL usage of fetching system values with QSH `sysval`

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#1122]
https://www.ibm.com/docs/en/i/7.3?topic=utilities-sysval

**Comment by worksofliam** [comment]
@chrjorgensen I know you helped work on this in the `IBMi.ts` connection process. What do you think?

**Comment by chrjorgensen** [comment]
I think we should use the fastest method, be it QSHELL `sysval` or SQL.

I already have some thoughts about the connection process and all the calls made to the server before the connection is complete. This takes quite some time for me and is a bit annoying. So I've done some testing measuring the time used per call and are considering how to reduce the number of calls by combining the requests. Nothing is ready yet - and maybe never will... 😆

**Comment by worksofliam** [comment]
@chrjorgensen I wonder if we could actually do some of the optional feature checking after the connection has been established. 

E.g. 

1. find out all the import stuff first (SQL, CCSID and data areas come to mind), then load the extension
2. let the user do stuff while the backend determines the remainder of the optional functionality

Likely another big change on top of all our PRs right now :joy:

I was also just thinking tonight that is becoming a little long, even for fast connections

**Comment by chrjorgensen** [comment]
@worksofliam My idea is to store the server settings, which are rarely changed, in some cache store in the client, and have a `Quick Connect` checkbox in the connection settings, that when checked will use the values in the cache (if available) instead of going to the server. The user can then remove the checkmark to refresh or force the client to get the newest values from the server.

Values that could be stored in cache are (in no particular order)
- bad data areas
- SQL
- CCSID
- encoding values for #@$
- ASP info
- all remote features
- temp library creation
- temp library features creation, i.e. GENCMDXML and GETNEWLIBL

The cache would be written after each connect to be available at next connection, whether the `Quick Connect` was selected or not. Then the user could just check it to have faster connections in the future.

Other stuff that could be run in the background on the server
- cleaning temp library
- cleaning temp directory

That would reduce connection time considerably...
