### ISSUE TITLE
Deleting a file with a SYMLNK causes IFS Browser to fail

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/vscode-ibmi#1299]
If I delete a file with a symbolic link the IFS Browser cannot display the filter.
To recreate:
```
touch file1
ln -s file1 symlnk
```
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/67484051/77f247ad-ac0b-49b4-9edc-16b25993548b)
Delete the file:
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/67484051/a729172e-26e7-4380-8ad5-9949c4c6f4e8)
Result:  File deleted, SYMLNK remains and IFS browser is no longer functional.
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/67484051/2ae64355-6b7a-44c9-bd9a-e5f5e0125573)
If I delete the SYMLNK external to VS Code, then the IFS browser returns to normal.

* QCCSID: 37
* Features:
   * git: true
   * grep: true
   * tn5250: true
   * setccsid: true
   * md5sum: true
   * bash: true
   * chsh: true
   * GENCMDXML.PGM: true
   * GETNEWLIBL.PGM: true
   * QZDFMDB2.PGM: true
   * startDebugService.sh: true
   * attr: true
   * iconv: true
* SQL enabled: true
* Source dates enabled: false

Variants
```json
{
  "american": "%23@$",
  "local": "%23@$"
}
```

Errors:
```json
[
  {
    "command": "system \"CRTLIB LIB(LENNONS2) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPD0032: Not authorized to command CRTLIB in library *LIBL.\nCPF0006: Errors occurred in command.",
    "cwd": "/home/LENNONS"
  },
  {
    "command": "system \"DLTOBJ OBJ(LENNONS2/O_*) OBJTYPE(*FILE)\"",
    "code": 255,
    "stderr": "CPF2125: No objects deleted.",
    "cwd": "/home/LENNONS"
  }
]
```

**Comment by sebjulliand** [comment]
@worksofliam , @chrjorgensen I'll fix that. However, I need your point of view so we can agree on the solution
That's the `--dereference` or `-L` flag making `stat` or `ls` fail. So I can think of three approaches to fix this:
1. Following symlinks isn't useful for the IFS browser, we take out the `--dereference` flag for both `stat` and `ls`: case closed
2. The `-L` flag isn't deemed useful with the `ls` command, so we take it out (because the command fails entirely when there is a broken link). We keep following symlinks with stat and handle the failure since it only fails on the symlink (the rest of the folder is still listed).
3. We add an option in the settings to `Follow symlinks` in the IFS browser so that users can at least turn this option off to prevent the IFS browser from failing when that happens.

I'm not sure following symlinks is very useful in the IFS browser, so I would go with option 1, but I need your opinion before doing something stupid 😉

**Comment by chrjorgensen** [comment]
@sebjulliand @worksofliam IMHO symlinks are very useful, and I would be sad to not have this option anymore...

I think there may be a 4th option: Since `ls` and `stat` also return data in stdout when there's an error 1, we could ignore error code 1 and still use stdout... and send stderr to warning messages... this would populate the IFS browser tree and warn the user of the problems at the same time...

WTYD?

**Comment by sebjulliand** [comment]
I completely agree with you @chrjorgensen about the usefulness of symlinks! I'm just questioning the use of `--dereference` in our context.

Also, you're right: both `ls` and `stat` use the code 1 to report a minor issue (I thought only `ls` did). But it seems that `stat` doesn't list the broken link. And for some reason `sendCommand` returned an error code 2 with `ls` and didn't list the broken link either.
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/11096890/3a056814-2e5f-4a1e-8259-44939b51c8a3)

However, removing the `-L/--dereference` flag will just not follow the link, it will still be listed even if broken. For what we do with `ls`, there should be no impact. For `stat`, it will display the information about the link itself and not the file it's supposed to points to.

**Comment by chrjorgensen** [comment]
Removing `-L/--dereference` would make the error go away and the tree being populated - with the symlink in error included and no warning issued. And the user would have to guess why the file can't be opened when clicking on it.

My suggestion is to keep the current behavior and use the content from stdout in the tree view - and any content from stderr as error messages. This to me seems like the best solution, since all errors would be shown to the user and all good content can still be viewed in the tree and accessed.

And if no good content is available, stdout will be empty and no tree will be populated. This could be caused by e.g. authorization errors or similar more severe errors.

Ah, these pesky error situations... 😆

**Comment by sebjulliand** [comment]
> Removing `-L/--dereference` would make the error go away and the tree being populated - with the symlink in error included and no warning issued. And the user would have to guess why the file can't be opened when clicking on it.
> 
> My suggestion is to keep the current behavior and use the content from stdout in the tree view - and any content from stderr as error messages. This to me seems like the best solution, since all errors would be shown to the user and all good content can still be viewed in the tree and accessed.
> 
> And if no good content is available, stdout will be empty and no tree will be populated. This could be caused by e.g. authorization errors or similar more severe errors.
> 
> Ah, these pesky error situations... laughing

Agreed! Here we go then: https://github.com/halcyon-tech/vscode-ibmi/pull/1302
