### ISSUE TITLE
Settings: Show Terminals and Debug tab even if not applicable 

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#1314]
Currently, the Terminals and Debug tabs are hidden if the user is missing specific user features that make the settings useful. They are also never shown when the Settings view is opened from the server browser.

I think we can improve the UX here, as it did prove to be confusing when they were not shown.

* If opened from the Server Browser: say to the user that these settings will be shown when the user has connected to the system
* If open after the user has connected, we have a couple of options:
   1. show the tabs, but display a message saying that the required server components are not installed and therefore cannot be changed.
   2. show the tabs, let the the user edit the settings, but note to them that the feature is missing

**Comment by chrjorgensen** [comment]
IMHO I think the Terminals and Debug tabs should always be shown, regardless of a connection to the server. It is confusing that they are not always there.

And showing a warning if the features are missing is a great idea - together with the tabs always being available, this is much more user friendly and may even trigger some users to try out the features, who would otherwise not know about them.

The documentation on the settings could also be improved - note to self... 😄
