### ISSUE TITLE
PUB400 and /QIBM/ProdData/IBMiDebugService/bin/certs

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/vscode-ibmi#1315]
On PUB400 we don't have access so can't run the debugger.  

If it is unsafe on PUB400 to open up the /QIBM/ProdData/IBMiDebugService/bin/certs directory to public use, perhaps this can be made configurable to let us use something in our home directory

![image](https://github.com/halcyon-tech/vscode-ibmi/assets/67484051/7b2c9d36-7607-4752-ad34-951cd18d7469)

![image](https://github.com/halcyon-tech/vscode-ibmi/assets/67484051/4411e94c-2efb-445b-916c-3e7a7701e4e3)

![image](https://github.com/halcyon-tech/vscode-ibmi/assets/67484051/4d4764f4-66b9-47ba-ac5c-a2253eec0695)

* QCCSID: 37
* Features:
   * git: true
   * grep: true
   * tn5250: true
   * setccsid: true
   * md5sum: true
   * bash: true
   * chsh: true
   * GENCMDXML.PGM: true
   * GETNEWLIBL.PGM: true
   * QZDFMDB2.PGM: true
   * startDebugService.sh: true
   * attr: true
   * iconv: true
* SQL enabled: true
* Source dates enabled: false

Variants
```json
{
  "american": "%23@$",
  "local": "%23@$"
}
```

Errors:
```json
[
  {
    "command": "system \"CRTLIB LIB(LENNONS2) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPD0032: Not authorized to command CRTLIB in library *LIBL.\nCPF0006: Errors occurred in command.",
    "cwd": "/home/LENNONS"
  },
  {
    "command": "system \"DLTOBJ OBJ(LENNONS2/O_*) OBJTYPE(*FILE)\"",
    "code": 255,
    "stderr": "CPF2125: No objects deleted.",
    "cwd": "/home/LENNONS"
  }
]
```

**Comment by Starcomfr** [comment]
Ok but why not allow to set manually the certificate directory ?
If certificates are in /home/xxxxxx/ it will work ? Am I wrong ?

**Comment by worksofliam** [comment]
@Starcomfr you can change the directory for the certs in the connection settings, though this likely won’t work for pub400 as there is usually only a single instance of the debug service.

**Comment by Starcomfr** [comment]
I am probably bad because I can't find this setting.

![Code_-_Insiders_2023-08-03_09-08-59](https://github.com/halcyon-tech/vscode-ibmi/assets/8850081/a48cf9c9-27b1-4489-8853-3a7ee0975237)
![Code_-_Insiders_2023-08-03_09-09-50](https://github.com/halcyon-tech/vscode-ibmi/assets/8850081/654e57ae-82fe-43a4-99cd-9b6e1df78c9c)
![Code_-_Insiders_2023-08-03_09-10-30](https://github.com/halcyon-tech/vscode-ibmi/assets/8850081/572a628e-c5f6-4ef7-9a2c-60c96c59bb8e)
![Code_-_Insiders_2023-08-03_09-11-01](https://github.com/halcyon-tech/vscode-ibmi/assets/8850081/1444be94-d8bf-4b56-8d67-cdee82dac4bc)
![Code_-_Insiders_2023-08-03_09-12-02](https://github.com/halcyon-tech/vscode-ibmi/assets/8850081/c2c45fed-8438-453f-9d1d-bc6aa9dbf5bd)

**Comment by worksofliam** [comment]
@Starcomfr its under the debugger tab when connected to the system.
