### ISSUE TITLE
Support for local workspace project

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#291]
Video preview: https://www.youtube.com/watch?v=wVbCofE1n6Q

---

We're moving to a time where git on IBM i for RPGLE, COBOL, CL, etc is finally becoming a thing.

We need to offer a way for people to clone onto their local machines, edit locally but compile on the IBM i.

Here are my thoughts as bullet points:

* User is working on the source in their local workspace/folder
   * User needs to be connected to their IBM i as usual
   * Command + E works the same.
   * They select their Action that they would like to run
   * Source copies to the build library and runs the action
       * Need to determine if copying to streamfile or source member based on Action used
       * Maybe local filesystem gets a different Action type. For example, there is `member`, `streamfile` and `object`. Should we add `local` for local actions?
       * Should local actions not even be tied to a connection? Maybe project actions should be defined in the json configuration for the project so all devs have the same action?
 
* Thoughts on copying source:
   * When copying source, we also need to copy any deps that source code has.
   * This includes any files references in copy / include statements from all the ILE languages (RPG, C, CPP, COBOL)
   * If `deleteSourceAfter` is true, we'd need to delete all source that was copied to the IBM i when it is done.
   * Instead of parsing the source code to find the include and copy statements, it might be easier to just do a raw search for everything in the users workspace in the source they are compiling. if the filename is found, then perhaps it is considered a dep.

* Each local workspace needs a `.vscode/ibmi.json` file, which will be used for some compile options
   * This file would be committed into the repo so every developer has it
   * Configuration might be:  `{buildLibrary: string, deleteSourceAfter?: boolean}` - can't think of any other props right now.
   * `&OPENLIB` and `&BUILDLIB` would be the `buildLibrary` variable

* `ibmi.json` would respect `.env` **and** Action IFS variables like `&NAME`, `&EXT`, `&CURLIB`, etc. If the user has these files:

```shell
#.env
BUILD_LIBRARY=USERLIB
```

```json
// .vscode/ibmi.json
{
  "buildLibrary": "BUILD_LIBRARY",
  "deleteSourceAfter": true
}
```

Then, the object would build into `USERLIB`.

* Thoughts on errors
   * Errors from `EVFEVENT` point to paths on the remote system.
   * We need to translate to paths on the local system so the errors show up correctly.

---

**Thoughts and ideas are welcome**

**Comment by worksofliam** [comment]
Video preview: https://www.youtube.com/watch?v=wVbCofE1n6Q

**Comment by onewheelonly** [comment]
Looks good! I really like the idea.

Not related to your enhancement, but you might prefer to use the extension `.rpgleinc` for your header files. That's one of the extensions the compiler supports (i.e. it will autofill it if you omit it from your `/INCLUDE` path).

https://www.ibm.com/docs/en/i/7.4?topic=directives-copy-include

> Instead of parsing the source code to find the include and copy statements, it might be easier to just do a raw search for everything in the users workspace in the source they are compiling. if the filename is found, then perhaps it is considered a dep.

I would worry about the performance of this on a large project. Another alternative might be something like `rsync` with SSH to synchronise the entire local workspace with a remote one, but that has a higher, one-off set up cost.

The `rsync` approach probably wants you to work in a different way. It seems like the kind of thing you would combine with a build tool like `make`. Whereas that doesn't seem like what you're (currently) aiming for with this. It would be cool if this could support both ways of working. There's at least some overlap, with the issuing remote commands and parsing `EVFEVENT`.

Another tiny consideration: as well as the `EVFEVENT` paths needing translation, the source debug views won't be available if you don't retain the source (duh) - which is something else that would push me personally towards a permanent project mirror on the i.

Either way, excited to see where you take this 🙂

**Comment by worksofliam** [comment]
> Another alternative might be something like rsync with SSH to synchronise the entire local workspace with a remote one, but that has a higher, one-off set up cost.

While this is another way, I am actually avoiding doing a full mirror to the IBM i. If the project is massive, then why would I want to copy everything when in reality I only want my current file and the stuff it depends on? I do plan on adding something where it will not upload the file again if the local copy has not changed (vscode stores versions of files to understand if it has changed!).

> Whereas that doesn't seem like what you're (currently) aiming for with this. It would be cool if this could support both ways of working.

It would be cool, I agree. While I likely won't add that support initially, I am planning on adding a command to generate a JSON dependency listing (which includes what Action was used to compile it maybe?) which can then be used to generate a makefile or by external build systems.

> Another tiny consideration: as well as the EVFEVENT paths needing translation,

Already handling that! https://github.com/halcyon-tech/vscode-ibmi/blob/00685ae5e3d6d9fb3790a7a26d6e706bed701927/src/api/CompileTools.js#L105

> the source debug views won't be available if you don't retain the source (duh) - which is something else that would push me personally towards a permanent project mirror on the i.

Yes, this is an initial.. which is why default the sources will not be deleted from the remote system. It will eventually be an option to delete them after the compile, but not from the start.

**Comment by worksofliam** [comment]
For the time being, I am going to leave the branch open but not continue any further with this idea as it is a very large feature.

**Comment by worksofliam** [comment]
After a discussion with IBM, they would rather me follow their standard instead of me implement my own and go against their idea. 

Created #298 for that.

**Comment by worksofliam** [comment]
@dennisnel please refrain from copy and pasting comments between issues. This also has no relevance here.

**Comment by richardm90** [comment]
Just to add a big thumbs up for this feature.

I've been looking at something like this for a while now. I think it would be hard to implement for larger existing applications, with a lot of source files I would imagine that keeping the source insync would be a struggle. I'm tending to work on a lot of smaller discreet git repos and this feature would be ideal for those. Because the source is currently being held on the server I've dropped back to using the git client cli to achieve a reasonable response so lose the benefits of the slicker git client ui's.

My vote would be to utilise a standard system (i.e. ibmi-bob) for syncing and building source, gain the benefits of a larger developer pool. I did try working with bob a few years back but didn't take it any further at the time because of concerns for the need to maintain a list of dependencies, it felt like this was going to become a lot of work; especially when you're dealing with hundreds if not thousands of source files. However for my smaller discreet projects I think it could work.

I know Mihael Schmidt also uses make as a build engine for his projects (e.g. https://bitbucket.org/m1hael/ipkg/src/master/) and it's something I've personally wanted to investigate to see if the method he uses could also work for my projects.

To be honest for my smaller projects these days I tend to create a CL program that builds the entire app (from IFS source), which is basically a list of compile commands so creating and maintaining a makefile or similar probably wouldn't be any harder, it may even be easier.

I'm with @onewheelonly regarding the `.rpgleinc` extension, I use this extensively.

When compiling a `local` source file I originally thought this would be copied to an IFS location (possibly configured to a temp folder in my home directory?) for compilation and would therefore use the `streamfile` compilation commands though maybe there could be a configuration option that specifies whether the `local` source file is copied to a `member` or a `streamfile`. Personally I can't think why I wouldn't want this going to the IFS unless the target release or member type didn't support `streamfile` compilation. I don't see a need for another set of `local` compilation actions, the compilation happens remotely so I think it makes sense to use the `member` or a `streamfile` compilation actions. Maybe there are other non-remote actions that may be applicable only to `local` source.

I would imagine copying the dependencies could be problematic or at least identifying the dependencies. I make extensive use of copy source files and of course copy source files can also reference other copy source files. It seems a shame to manually maintain a list of inter-dependencies in a makefile (or similar) when the information is available in the source. Maybe if a source file changes the inter-dependencies for that source could be interrogated and the relevant section of a makefile updated.

I agree that the errors would need to be appropriate to the local source and reflected accordingly in VS Code.

This is looking really good, very impressed!

**Comment by richardschoen** [comment]
I absolutely love the idea of editing from the IFS and simply running a compile action to upload/build a de-buggable object right away. That's something most IBM i developers (even classic ones) could potentially adapt to. 

Then you could simply debug from the green screen or if IBM would open up the debug calls to you, you could make debugging fully work from VS Code. 

What you're proposing is short, sweet and simple day-to-day coding workflow for IBM i devs.

I don't know exactly what IBM is proposing, but I think going the make route and forcing usage of rsync for moving files is not a step in the right direction and doesn't make life easier for the standard IBM i dev.  I would really need to see what they are planning to do and hear their justification to know if it's better. 

Building IBM i apps with RPG/CL is still a bit different than most project based languages like .Net, Java, Node, etc, so let's not force that style of build process on devs by default. 

What you're doing here hits the mark for most of the day-to-day IBM i devs. 

Keep up the good works.  And hopefully the IBM team will get on board and see the value of this rather than trying to re-invent the wheel.  It's already round.

**Comment by worksofliam** [comment]
Implemented in vscode-rpgle.
