### ISSUE TITLE
Show program references

### ISSUE THREAD

**Issue by szsascha** [halcyon-tech/vscode-ibmi#306]
**Is your feature request related to a problem? Please describe.**
How cool would it be to have a view of the whole call hierarchie of programs? 

**Describe the solution you'd like**
There is a pretty useful command called "DSPPGMREF" (https://www.ibm.com/docs/en/i/7.1?topic=ssw_ibm_i_71/cl/dsppgmref.htm)
It just came to my mind so I don't have a specific idea how this can be utilized. But I think it can be a pretty nice feature for this extension.
But I'm not thinking about creating a single DSPPGMREF. The command should be executed over and over until the last program of the stack was found.
I'm just writing down my thoughts here. Maybe we'll create nice features out of it.

**Comment by onewheelonly** [comment]
At our company, we dump the references for our application libraries to a table using the OUTFILE mode of DSPPGMREF. We've then got a green-screen interface that can query over this - this is generally used for "where is this object used?" style analysis.

Having a similar query interface available as an extension would be incredibly useful. It then gives a lot of flexibility over how you generate this data. Build it for entire libaries overnight (as we do)? Update it in real time for individual programs, as part of your build? Since it's just the output from an IBM command, it is easy enough to script either way.

**Comment by worksofliam** [comment]
As a note, `DSPPGMREF` to outfile, as well as `DSPMOD OUTFILE`

**Comment by worksofliam** [comment]
Going to mark as stale until we can fully understand how this should be used.

**Comment by bashdi** [comment]
I once wrote a programm in java, which executed a DSPPGMREF and exported the outfile as [graphdot/graphviz](https://en.wikipedia.org/wiki/DOT_(graph_description_language)) and csv. I then used [gephi](https://gephi.org/features/) to create visualizations. 

Maybe there is a way to do a simple preconfigured visualization in vscode. 

Right-click on src/member -> DSPPGMREF ->
- Export as CSV
- Export as dot
- Visualize

**Comment by worksofliam** [comment]
I personally believe this should not be in the base. This is a simple enough task and I would be happy to work with anyone who is interested in building it. In the extension, you can hook right into Code for IBM i to run commands and download content. 

Feel free to reach out to me on Twitter if you want to work on it and I'd be happy to give any guidance. 

* https://github.com/halcyon-tech/vscode-ibmi/blob/master/docs/api/extending.md
