### ISSUE TITLE
CL Content Assist Cursor Position Issue

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/vscode-ibmi#317]
**Describe the bug**
Cursor position when you hit ctrl+space can result in "No suggestions".
**To Reproduce**
1. Enter addlible and leave the cursor right after the e. Press Ctrl+space. Result:
![image](https://user-images.githubusercontent.com/67484051/134388194-592c7074-48cb-47d7-a5e4-96587bc7d8fe.png)

2. Add a space after the e. Press Ctrl+space.  Results as expected:
![image](https://user-images.githubusercontent.com/67484051/134388402-07c2a5be-d0a8-4e1a-b670-fa88744cf3a7.png)

3. Leaving the cursor on the command also results in "No Suggestions":
![image](https://user-images.githubusercontent.com/67484051/134389722-52310a31-a0c2-4e3d-acf9-59538d0990f8.png)

4. I see a lot of console messages similar to this:
![image](https://user-images.githubusercontent.com/67484051/134390136-e63a166c-08cd-495d-b967-1007ebab7a6a.png)
Detail like this:
![image](https://user-images.githubusercontent.com/67484051/134390403-1360167a-773d-4645-bed4-a202a0d94c1c.png)
Looks like only text to the left of the cursor is being passed to GENCMDXML. (And perhaps a MONMSG might be in order.0 

**Expected behavior**
Hopefully I'm understanding how content assist should work.

**Comment by worksofliam** [comment]
Based on your item numbers:

1. Leaving the cursor directly at the end of the word `addlible` will not prompt the command since VS Code doesn't provide a list of available commands via the content assist
2. Works as expected because now the cursor is past the word, it knows what command to prompt on
3. As expected.
4. I will look into those errors, but note we actually catch that when the prompt crashes in our backend since we can use that to determine if the command exists.

Liam

**Comment by worksofliam** [comment]
Looked into 1 and 3 more - which is what causes number 4.

Prompting on `ADDLIBLE`

1. When you prompt at index 4 of `ADDLIBLE`, it thinks you're looking for the command `ADDL` (partly due to implementation, but prompting when your cursor is on the command is not valid anyway). Then it's running `GENCMDXML` on `ADDL` and not `ADDLIBLE`.
2. When you prompt at the very end of `ADDLIBLE`, it is fetching the command correctly, but is looking for parameters that start with the word the cursor is on - in this case, that is `ADDLIBLE`, and there are no parameters which start with that.

Liam

**Comment by worksofliam** [comment]
@SJLennon I think it's time to close this. What do you think?

**Comment by SJLennon** [comment]
I haven't yet managed to experiment more on this.  Seems like it might be something that needs explanation in the help-my confusion was, I think, trying to use it as you would prompting in SEU of the OS command line.
But ti can be closed.
@worksofliam
