### ISSUE TITLE
Config to change default wait time for connection 

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#336]
As suggested by @ChrisHird, we should add configuration to let the user change the wait time for the SSH job.

https://www.ibm.com/docs/en/i/7.2?topic=jobs-getjobid

```
# Store the job ID from this. Happens when connection is made
getjobid $$ 

# Use the JOB id here. Happens when connection is made
system "CHGJOB JOB(x) DFTWAIT(x)"

# Any future system commands will inherit it
system "CPYTOSTMF ..."
```

**Comment by worksofliam** [comment]
There is a bit of an issue. I didn't know this, but it looks like `paseCommand` (node_ssh / ssh2 `exec` / `execCommand`) is actually forking the connection process when running a command.

I'm at a point here where I am unable to get the actual connection job ID because it's running the `echo` in a forked process? 

Happening here in this PR:

https://github.com/halcyon-tech/vscode-ibmi/pull/337/files#r717036957

**Comment by worksofliam** [comment]
It may have something to do with channels being opened for every command. See `exec` here: https://github.com/mscdex/ssh2#client-methods

**Comment by ChrisHird** [comment]
Not sure if I am reading it correctly but you are doing 2 await requests at the same time, so they would be different requests and probably fork to different processes???

If the request is not put in an await request the process should be the same as the one the requests run under? If a request comes in and the jobs is tied up waiting to respond to the previous request it probably spawns another job???

That would make sense with my limited knowledge.  😊 Not sure if that helps or not..

Chris…

**Comment by Dman247** [comment]
Yes, I am seeing both `exec()` and `execCommand()`  create separate processes as well.

Next steps I would consider are to run the copy commands, that error out due to lock, through a shell.
There, you can definitively grab the jobid for the shell that was spawned and perform the CHGJOB on it.
All subsequent commands running through that shell should have the same job attributes the shell had. (I've done a primitive test of this and it seems to work)

Otherwise, I don't know how you would identify the right sshd job to change the DFTWAIT with, because we have to assume there could be numerous ssh connections on the system:
![image](https://user-images.githubusercontent.com/38368303/135002051-2077c4a9-cf4a-4d4f-a7f5-cb2123063ef2.png)

In the example above example here, one of those is my ssh connection from the extension and another is an ssh for a remote shell.

What is interesting, the IBMi job that supports the connection back to the extension has something unique logged in the job log.
![image](https://user-images.githubusercontent.com/38368303/135003436-71d7b476-e708-4bcc-93f7-bb27d902369d.png)
The blanked out blobs identify the IP and Port numbers.
So, if we were still determined to change the job of the connection... I guess we could go scouring through every SSHD job's joblog to find a match to our username/IP? Seems a bit much.

I think running the copy commands through a shell will be cleaner.

**Comment by worksofliam** [comment]
@Dman247 Thanks for your great research here.

> Next steps I would consider are to run the copy commands

Would you provide those commands here too? I will try and update my PR to run them in the connection.

> I guess we could go scouring through every SSHD job's joblog to find a match to our username/IP? Seems a bit much.

You are right, it is a bit much. I would likely never do this. It's not worth the hassle.

**Comment by Dman247** [comment]
Yup, so it ends up being this one right here:
https://github.com/halcyon-tech/vscode-ibmi/blob/a860343eccfb1dceaf47a8e415d2ca49e677eb26/src/api/IBMiContent.js#L66-L68
If when we try to attempt that copy we use something like this screenshot to request/use the shell:
https://github.com/halcyon-tech/vscode-ibmi/issues/217#issuecomment-927499507

And here's a one-liner that should change the shell's DFTWAIT to 1 second:
`system "CHGJOB JOB($(getjobid -s $(echo $$))) DFTWAIT(1)"`

**Comment by worksofliam** [comment]
@Dman247 I will give that command a go in the PR and I will post back here.

Thanks so much!

**Comment by worksofliam** [comment]
There is a stale PR for this and it hasn't had much work and people haven't been talking about this that much so I will assume it's not really required or wanted. I think if someone has the time, they could pick the PR up and continue the fork to implement it.
