### ISSUE TITLE
Reconnect and disconnect option.

### ISSUE THREAD

**Issue by GajenderI** [halcyon-tech/vscode-ibmi#362]
**Is your feature request related to a problem? Please describe.**
When ever connection is lost there is no option to reconnect, I have to close vs code and open again for connecting. 

**Describe the solution you'd like**
An option for my current connection to disconnect and reconnect.

**Describe alternatives you've considered**
Close vs code session and open again.

**Comment by SJLennon** [comment]
I agree it would be nice to be able to reconnect and not lose un-saved work.

@GajenderI In the interim,  rather than restarting VS Code, you might want to try disconnecting with F1 and report if it works.:
![image](https://user-images.githubusercontent.com/67484051/139690754-1b12f7e2-66fa-46a7-a0bf-3d6d7210d62d.png)

**Comment by SJLennon** [comment]
"Tested" this out this morning.  Excellent.  I think folk will appreciate this.  👍 
@worksofliam

**Comment by worksofliam** [comment]
Thanks @SJLennon !! Glad you think so.

**Comment by GajenderI** [comment]
@SJLennon  Thanks for the information the command for disconnect works fine. 
 Thanks to both of you for considering the new feature of reconnect.

**Comment by SJLennon** [comment]
@worksofliam Tried to do Ctrl+e. 
![image](https://user-images.githubusercontent.com/67484051/142909395-0d1be903-e1ad-4041-986a-368d2498f455.png)
Was sure this had been fixed? 
This is the Code for IBM i output:
```
LENNONS1/JOBLOGMSG       PUB400     11/22/21 16:08:06        Page      7\n                           M e s s a g e   S u m m a r y\n  Msg id  Sv Number Message text\n *RNF5409 00      1 The prototyped call returns a value which is lost when CALLP\n                    is used.\n *RNF7031 00      1 The name or indicator is not referenced.\n *RNF3901 20      2 Keyword is not allowed for a constant definition; keyword is\n                    ignored.\n *RNF5377 20      1 The end of the expression is expected.\n        * * * * *   E N D   O F   M E S S A G E   S U M M A R Y   * * * * *\n                                                    -=* http://pub400.com *=-\n  5770WDS V7R4M0  190419 RN        IBM ILE RPG             LENNONS1/JOBLOGMSG       PUB400     11/22/21 16:08:06        Page      8\n                             F i n a l   S u m m a r y\n   Message Totals:\n     Information  (00) . . . . . . . :        2\n     Warning      (10) . . . . . . . :        0\n     Error        (20) . . . . . . . :        3\n     Severe Error (30+)  . . . . . . :        0\n     ---------------------------------  -------\n     Total . . . . . . . . . . . . . :        5\n   Source Totals:\n     Records . . . . . . . . . . . . :       20\n     Specifications  . . . . . . . . :       14\n     Data records  . . . . . . . . . :        0\n     Comments  . . . . . . . . . . . :        3\n          * * * * *   E N D   O F   F I N A L   S U M M A R Y   * * * * *\n Compilation stopped. Severity 20 errors found in program.\n           * * * * *   E N D   O F   C O M P I L A T I O N   * * * * *\n                                                    -=* http://pub400.com *=-",
    "stderr": "RNS9308:  Compilation stopped. Severity 20 errors found in program.\nCPC0904:  Data area RETURNCODE created in library QTEMP.\nRNS9310:  Compilation failed. Program JOBLOGMSG not created in library LENNONS1."
}

/home/LENNONS: system "QSYS/CPYTOIMPF FROMFILE(LENNONS1/EVFEVENT JOBLOGMSG) TOSTMF('/tmp/vscodetemp-oHUZWz2zJV') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM(',') DECPNT(*PERIOD) "
{
    "code": null,
    "signal": null,
    "stdout": "CPC2958: All records copied from file EVFEVENT in LENNONS1.",
    "stderr": ""
}

.: system "CPYTOSTMF FROMMBR('/QSYS.lib/LENNONS1.lib/TEMP.file/JOBLOGMSG.mbr') TOSTMF('/tmp/vscodetemp-oWP9A5CTxC') STMFOPT(*REPLACE) STMFCCSID(1208) DBFCCSID(*FILE)"
.: system "CPYTOSTMF FROMMBR('/QSYS.lib/LENNONS1.lib/TEMP.file/JOBLOGMSG.mbr') TOSTMF('/tmp/vscodetemp-oWP9A5CTxC') STMFOPT(*REPLACE) STMFCCSID(1208) DBFCCSID(*FILE)"
/home/LENNONS: echo "liblist -d LENNONS1 LENNONS2 QTEMP QGPL;liblist -c LENNONS1;liblist -a QGPL QTEMP LENNONS2 QIWS LENNONS1;system  \"CRTBNDRPG PGM(LENNONS1/JOBLOGMSG) SRCFILE(LENNONS1/TEMP) OPTION(*EVENTF) DBGVIEW(*SOURCE) TGTRLS(*CURRENT)\"" | /QOpenSys/usr/bin/qsh
```
This is all I see for connections:
![image](https://user-images.githubusercontent.com/67484051/142910474-84dcfd2d-e7dd-4365-9274-f4db73051b45.png)

Refresh connections doesn't anything.

**Comment by worksofliam** [comment]
@SJLennon Looks like that error is due to you being disconnected when trying to save a file. I guess you should have been notified about the disconnect, but the ssh connection doesn't always know it's been disconnected until you try to do something.

'Refresh connections' is used to refresh the initial connections UI.

**Comment by SJLennon** [comment]
Yes, it was disconnected, but 18 days ago I had a timeout issue and that allowed me to reconnect.  Would it be possible to allow that same re-connection logic to kick in here?  
![image](https://user-images.githubusercontent.com/67484051/142924232-276396bc-be9d-456a-894e-9ba70367190f.png)
Otherwise there is no way out (short of closing down VS Code) because you can't disconnected with unsaved files and you can't save either. 
I tried opening another member and it just did nothing, didn't even appear to throw an error, so I accept that it might be tricky to catch disconnected sessions and may be low priority.
One workaround is to open a second VS Code instance or window, connect from there, and copy and paste changes.
@worksofliam

**Comment by sagartyagi121** [comment]
This has been fixed, I hope you have the latest version of extension.

**Comment by SJLennon** [comment]
@jkyeung Is this your setup and it still has issues?
![image](https://user-images.githubusercontent.com/67484051/176479614-f7ea77ff-cf3d-415e-acf1-074a829d4aee.png)

**Comment by SJLennon** [comment]
@jkyeung 
> I am a little surprised that "force reconnect" is not in the command palette. So the only way we can get it is with that button?

See discussion #477 is the only answer I can give.  I did add it to the documentation, though.
