### ISSUE TITLE
Import PDM options

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#367]
I think it would be cool to import PDM options right into actions.

Perhaps we should only import commands that begin with `CRT`?

Would love thoughts on this.

**Comment by SJLennon** [comment]
The idea may help some folk transition from PDM/SEU.  But some thoughts...

I've looked at my PDM options and I don't have a lot of CRT... ones.  Options 14 & 15 usually worked for me.  My CRT... options:
```
CD    /*Compile DSPF*/ CRTDSPF FILE(&L/&N) SRCFILE(&L/&F) SRCMBR(*FILE)
CQ    /*Create QMQRY*/ CRTQMQRY QMQRY(&L/&N) SRCFILE(&L/&F)
XC    /* Compile CL*/CRTBNDCL PGM(&L/&N) SRCFILE(&L/&F) DBGVIEW(*SOURCE 
XS    CRTSQLRPGI OBJ(&L/&N) SRCFILE(&L/&F) SRCMBR(&N) DBGVIEW(*SOURCE)  
XX    CRTPRTF FILE(&L/&N) SRCFILE(&L/&F) ??PAGESIZE(66 132)
```
Personally, since I formerly used RDi and Aldon, and now VS Code, I haven't needed to use CRT... command much in PDM. 

For other than CRT... commands, many of mine would not work in VS Code

Some other thoughts:

1. I suppose you would name them with the PDM 2-Char "Option" and then the user could edit the name (2-chars is limiting and some of mine are low use and obscure, hence the comments ).  
2. Guess to which extensions the action applied.
3. Look for them in the default location (file QAUOOPT, member QAUOOPT)?  *LIBL?  They can be somewhere else.
4. I would like a **Delete Action** button. 

@worksofliam

**Comment by worksofliam** [comment]
@SJLennon 

> I suppose you would name them with the PDM 2-Char "Option" and then the user could edit the name (2-chars is limiting and some of mine are low use and obscure, hence the comments ).

I would name them `<COMMAND> (<SHORT>)`.

> Guess to which extensions the action applied.

Yes, I'd have to write some logic. Perhaps I could just put them all under `GLOBAL` otherwise.

> Look for them in the default location (file QAUOOPT, member QAUOOPT)? *LIBL? They can be somewhere else.

The default will be `QGPL/QAUOOPT`, but a text box will appear and the user can change the path.

> I would like a Delete Action button. 

Good idea. Likely needs a separate issue to track it. Feel free to create it.

**Comment by worksofliam** [comment]
I have been thinking about this some more size I read @SJLennon's comment and I am starting to wonder if this functionality would have any real value.
