### ISSUE TITLE
Output button on status bar that takes you to IBM i Output

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#470]

**Comment by SJLennon** [comment]
@worksofliam 
1) Are you suggesting replacing this with a button on the status bar?
![image](https://user-images.githubusercontent.com/67484051/150029591-76cc892b-f700-43a8-aad9-777e42ce1986.png)
If so, I would like that.

2) IBM i Output showing a compile listing is often handy.  But listings tends to build up unless cleared manually. Could IBM i Output be cleared automatically when a new compile is requested?

**Comment by worksofliam** [comment]
I was thinking about leaving that button, as well as a button on the status bar.

> Could IBM i Output be cleared automatically when a new compile is requested?

I like this a lot, but I should make it configurable. E.g. new config like 'clear IBM i Output for every Action' - enabled by default perhaps?

**Comment by SJLennon** [comment]
@worksofliam Personally, I find the big button a bit intrusive because it overlays the Problems tab and I usually click it away.  Of course, it depends on what kind of problems I'm having with the code and sometimes it is useful.

Agree on making 'clear IBM i Output for every Action' configurable and enabled by default.

**Comment by worksofliam** [comment]
@SJLennon with some user testing I may take it away. Right now, that 'Show Output' button is there to tell users they can see the spool file since it is not obvious otherwise. This new status bar button may change that.
