### ISSUE TITLE
Database Browser is slow

### ISSUE THREAD

**Issue by JDubbTX** [halcyon-tech/vscode-ibmi#483]
Our data libraries have hundreds of tables, when first expanding a library - I get a spinning circle for several minutes, which does give me time to get coffee, but sometimes my coffee cup is already full.  Is there a faster way to get the list of objects to load?

**Comment by worksofliam** [comment]
@JDubbTX No. Right now, the database browser is not changed that often since I am plan on replacing it with a proper database extension (though I need time to do that also).

https://github.com/halcyon-tech/vscode-db2i

I may be able to temporarily add paging to the database browser, so it could load 200 rows at a time or something, with a 'more' button to load 200 more. I'd need to find the time to work on that also.
