### ISSUE TITLE
Allow me to replace some of the extension commands 

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-ibmi#493]
When I connect to our IBM system, I get the message `The data area QSYS/QCPTOIMPF exists on this system and may impact Code for IBM i functionality.`   I cannot change or alter the existence of this command on our system.  To reduce the amount of work to remove the old version of CPYTOIMPF with the newer one we created a custom command that matches the system command. 

I am not as concerned with seeing the message but I would like to perform the actions of copying to the IFS.   

We replaced CPYFRMIMPF as well. 

Thanks, Matt

**Comment by worksofliam** [comment]
@m-tyler I am not sure about this one. Of course, I can make it configurable, but it would take a lot of time for me to test and get it implemented.

**Comment by worksofliam** [comment]
The potential plan is to add a new configuration to let the user specify a 'command library' which will be used in place of QSYS. This will apply to all commands, because it won't be good to do it for just these two.

After some time thinking about it, the message that appears because of the data areas perhaps could go away if I let the user specify a different command library.

@m-tyler  Because of the nature of this issue, I am only going to implement it if this issue receives more feedback from other users.

**Comment by m-tyler** [comment]
A workaround for the CPYTOIMPF data area is to create the DTAARA into QTEMP.
`CRTDTAARA DTAARA(QTEMP/QCPTOIMPF) TYPE(*CHAR) LEN(6) VALUE('NO')`

**Comment by m-tyler** [comment]
Thinking about it more a separate command library might be the best option.  When we upgrade to new releases, we do DEV first, wait for a few weeks then do PROD.  This requires us to compile down uring the interim.   So if this tool was to hardcode to QSYS commands it will limit our ability to compile through the tool.

**Comment by worksofliam** [comment]
@m-tyler Right, the config would basically let the user which library all the commands exist in. But, I won't work on this until I get more feedback.
