### ISSUE TITLE
Anyway to get a possible source truncation warning?

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-ibmi#508]
**Is your feature request related to a problem? Please describe.**
I let rpglint clean my code up.  This included source lines that reached from col1 to nearly col 100 (our source is 100 characters).   In VS Code nothing looks odd but when the source is saved back to my server, it truncates code beyond col 100.

**Describe the solution you'd like**
Any chance rpglint can give a warning about a line length problem? 

**Describe alternatives you've considered**
A comparison by the tool to find the widest part of the code and compare it to the size of the source file.  

**Additional context**
You would need to capture the record length of the source file into the workspace to make it most effecient.

**Comment by JamesBrianHill** [comment]
@m-tyler - I never let rpglint clean up everything in one go. Actually, I rarely let it clean anything up at all - instead, I manually fix the problem it points out. Because of how I do things I've not experienced your exact problem.

By setting word wrap to 100 columns, I visually see when something is "off" and I correct it.  So far, I've always corrected things before saving so I've not experienced the issue.

Rulers are a standard feature of VSCode.  Go to settings and search for "ruler" and you should be able to edit settings.json to add one or more rulers where ever you want them.

**Comment by worksofliam** [comment]
Leaving this one open for now. Not sure how to make the rulers appear dynamically or if it's even possible.

**Comment by worksofliam** [comment]
Coming soon 

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/3708366/153978690-a5fa0dc3-1232-47c6-a118-5c731ecd5cf5.png">
