### ISSUE TITLE
Members disappeared

### ISSUE THREAD

**Issue by EMennen** [halcyon-tech/vscode-ibmi#520]
I work for sometime with vs-code IBMI and it works great!
But in the ObjectBrowser, where I have a filter MyLib/Q*/*ALL, I don't see any member. Even after a refresh.
The IFS browser works normal.
I got no errors.

**Comment by worksofliam** [comment]
Trying setting your SQL executor to 'none' in the connection settings.

**Comment by viruslogic** [comment]
Hello, first of all thank you very much for your work. 

Following the thread, I can confirm that since this morning I have the same problem. I got a vs code update and from that moment on I don't see any member in the Object Browser.

I have tried setting my SQL executor parameter in my connection settings to 'none' and I still have the same problem.

![ObjectBrowser](https://user-images.githubusercontent.com/10233590/153384498-3c6ddef5-2449-4d19-84fe-7f595d99e673.png)
![settings](https://user-images.githubusercontent.com/10233590/153384500-fd99416d-6461-4c7a-bc20-f9a41c7b09e8.png)
.

**Comment by viruslogic** [comment]
This is a problem with version 0.8.33 that was just released a few hours ago.

By downgrading to the previous version, 0.8.32, I can see the members again without any problems.

**Comment by worksofliam** [comment]
@viruslogic SQL executors was removed in 0.8.33.

In the new version, set SQL enabled to false.

**Comment by viruslogic** [comment]
@worksofliam by changing the enableSQL parameter to false, it works perfectly.

Thank you very much.

**Comment by worksofliam** [comment]
@viruslogic when you have a moment

1. Change it back to true and restart VS Code
2. Try and open a source file again
3. If it fails, go to the OUTPUT tab, switch the drop down to Code for IBM i 
4. Copy and paste entire log here. This will help me debug why.

**Comment by viruslogic** [comment]
Sure! No problem.

I attach the log in a txt file. At the end you can see the error. It's a character conversion problem.

You'll see the log in spanish, sorry...

[error.log](https://github.com/halcyon-tech/vscode-ibmi/files/8041130/error.log)

**Comment by worksofliam** [comment]
@viruslogic Added a piece of code to disable SQL mode when CCSID is 65535.

**Comment by viruslogic** [comment]
Hi @worksofliam, I have tried it and it still doesn't work

![error](https://user-images.githubusercontent.com/10233590/153434495-8453c22e-d20b-4e65-b74d-df7f8d72e5d4.png)
[error.log](https://github.com/halcyon-tech/vscode-ibmi/files/8041962/error.log)
