### ISSUE TITLE
Load Problems as you save

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#64]
It would be nice if the Problems window loading issues with your source when you saved (this is because we'd go back to the server to get us information).

In order to do this, we need to run compile commands with `OPTION(*EVENTF *NOGEN)`.

* `*EVENTF` generates the information/error listing
* `*NOGEN` stops the source from actually compiling

We'd need to add code to add these to the commands that support them. I believe the list of commands that support both these options are:

* `CRTBNDRPG`
* `CRTRPGMOD`
* `CRTSQLRPGI`
* `CRTBNDCBL`
* `CRTCBLMOD`
* `CRTBNDC`
* `CRTCMOD`
* `CRTCLMOD` - **it is not available on `CRTBNDCL`**

If anyone else knows other options that would speed up this command execution, please me know.

The developers would also have to specify which action they want to use to run the command. Since we won't know from just saving, it usually helps to have a directive in the source so we can use it and know which action to run without prompting the user. For example:

```
//compile:CRTSQLRPGI
/* compile:CRTCLMOD */
* compile:CRTBNDCBL
```

If one is not specified, then it will not run.

**Comment by SGI495** [comment]
I like the idea of getting problems listed automatically, but I'm not sure about the meta annotations in the sources. Unfortunately don't really have a better solution at the moment. Perhaps it can be deduced from the source member type or similar. 

Also consider that some users might have a lot of auto-saving going on since that's a basic VSCode feature.

**Comment by SJLennon** [comment]
Perhaps what you want is the equivalent of the "Verify" command in RDi.  This updates the error list (and refreshes the outline.)  I believe it runs the actual front end of the compiler which is portable code.  I don't expect IBM would make it available though, so you'd probably have to go and compile. 

Thus I suggest implementing a "Verify" button or command, so that if there is the overhead of going back to the server the user has control of when it happens.  

I also imagine you'd want to save the file to a temporary location and compile that.

@SGI495 @worksofliam
