### ISSUE TITLE
Change new filter entry view panel, Object type filter to be drop down list

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-ibmi#644]
When I create an action using an IBM i command I can code keywords with this `${KW|Text|Value}` or with this `${KW|Text|Value1, Value2, Valuen}`.    This second style forces the view panel to show the comma list as a drop-down.

Can this be done with the add new filter view?

**Comment by worksofliam** [comment]
So you're suggesting that instead of a textbox to enter in the different object types, you want a multiselect dropdown? Kind of like something on here?

https://bendera.github.io/vscode-webview-elements/components/vscode-multi-select/

Would you be willing to provide the entire list of object types @m-tyler? Or perhaps a link to some docs with them all?

Thanks
